### ISSUE TITLE
Why don't you just archive this?

### ISSUE THREAD

**Issue by AndrewDavis** [sinhrks/cesiumpy#81]
Hi, this project clearly doesn't work out of the box for basically anyone following the readme, and it's outdated. So why don't you just archive it and stop wasting everyones' time?

Thanks,

- everyone whose time you've wasted

**Comment by lucas-bremond** [comment]
@AndrewDavis

CesiumPy is a fantastic/very clever package, which I've been using successfully (yes, the current version is outdated, but I've forked it and made it work without too much trouble).

GitHub issues are not the place for harsh comments like yours.

**Comment by AndrewDavis** [comment]
> yes, the current version is outdated, but I've forked it and made it work without too much trouble

Thanks for making my point.
